package fr.univartois.butinfo.lensymphony.notes.decorator;

import fr.univartois.butinfo.lensymphony.notes.Note;
import fr.univartois.butinfo.lensymphony.synthesizer.NoteSynthesizer;

/**
 * Abstract decorator for {@link NoteSynthesizer}.
 * <p>
 * This class allows extending or modifying the behavior of an existing
 * synthesizer (e.g., adding harmonics, ADSR, vibrato, etc.)
 * without changing its structure.
 * </p>
 */
public abstract class DecoratorNoteSynthesizer implements NoteSynthesizer {

    /**
     * The base synthesizer being decorated.
     */
    protected final NoteSynthesizer base;

    /**
     * Creates a new decorator for the given synthesizer.
     *
     * @param base The synthesizer to decorate.
     */
    protected DecoratorNoteSynthesizer(NoteSynthesizer base) {
        this.base = base;
    }

    /**
     * Template method that delegates synthesis to the base synthesizer,
     * then applies the specific effect defined by the subclass.
     */
    @Override
    public double[] synthesize(Note note, int tempo, double volume) {
        double[] baseSound = base.synthesize(note, tempo, volume);
        return applyEffect(baseSound, note, tempo, volume);
    }

    /**
     * Applies the specific transformation or effect on the synthesized sound.
     *
     * @param samples The array of samples generated by the base synthesizer.
     * @param note    The note being played.
     * @param tempo   The tempo in BPM.
     * @param volume  The volume of the note.
     * @return The modified array of samples after applying the effect.
     */
    protected abstract double[] applyEffect(double[] samples, Note note, int tempo, double volume);
}