
package fr.univartois.butinfo.lensymphony.systhesizer;

import fr.univartois.butinfo.lensymphony.notes.Note;
import fr.univartois.butinfo.lensymphony.synthesizer.BassDrumSynthesizer;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for {@link BassDrumSynthesizer}.
 * Verifies sample generation for both regular notes and rests, taking tempo into account.
 */
class TestBassDrumSynthesizer {

    /**
     * Dummy note used for testing.
     */
    static class DummyNote implements Note {
        @Override
        public double getFrequency() {
            return 440;
        }

        @Override
        public int getDuration(int tempo) {
            return 500;
        }
    }

    /**
     * Tests that the raw sample generated by {@link BassDrumSynthesizer#computeRawSample(Note, double, int)}
     * is within the expected range.
     */
    @Test
    void testComputeRawSample() {
        BassDrumSynthesizer synth = BassDrumSynthesizer.getInstance();
        Note note = new DummyNote();

        double t = 0.1;
        int tempo = 120;
        double sample = synth.computeRawSample(note, t, tempo);

        assertTrue(sample >= -1.0 && sample <= 1.0);
    }

    /**
     * Tests that {@link BassDrumSynthesizer#synthesize(Note, int, double)} produces
     * a non-null array of samples and that each sample is within the expected volume range.
     */
    @Test
    void testSynthesize() {
        BassDrumSynthesizer synth = BassDrumSynthesizer.getInstance();
        Note note = new DummyNote();

        double[] samples = synth.synthesize(note, 120, 0.5);

        assertNotNull(samples);
        assertTrue(samples.length > 0);

        for (double s : samples) {
            assertTrue(s >= -0.5 && s <= 0.5);
        }
    }

    /**
     * Tests that synthesizing a rest note (frequency 0) produces an array of zeros.
     */
    @Test
    void testSynthesizeWithRest() {
        BassDrumSynthesizer synth = BassDrumSynthesizer.getInstance();

        Note restNote = new DummyNote() {
            @Override
            public double getFrequency() {
                return 0;
            }
        };

        double[] samples = synth.synthesize(restNote, 120, 0.5);

        for (double s : samples) {
            assertEquals(0, s);
        }
    }

}
